version = 1

test_patterns = ["*_test.go"]

exclude_patterns = [
    "assets/**",
    "data/**",
    "runtime/**",
    "tools/*.sh"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/siddhant-deepsource/micro"]

[[transformers]]
name = "gofmt"
enabled = true